version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  nightly:
    jobs:
      - nightly:
          filters:
            branches:
              only: master
          context:
          - sloshy
  test-pushed:
    jobs:
      - test-pushed:
          filters:
            branches:
              only: master
          context:
          - sloshy

jobs:
  nightly:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - run:
          name: "Run nightly scan if this wasn't triggered by a recent commit"
          no_output_timeout: 30m
          command: |
            commit_timestamp=$(git log --no-walk --format=%at HEAD)
            commit_age=$(($(date -u +%s) - commit_timestamp))
            if ((commit_age < 3600)); then
                echo "Commit age $commit_age < 3600 -- aborting"
                exit 0
            fi
            pip3 install -r requirements.txt
            python3 ./run.py --circle-ci
            curl -s https://hc-ping.com/${SLOSHY_HEALTHCHECK_UUID}

  test-pushed:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: "Code lint"
          command: |
            # Fail early for syntax errors etc
            flake8 --count --select=E9,F63,F7,F82 --show-source \
              --statistics *.py
            # If syntax is OK, provide statistics
            flake8 --count --exit-zero --max-complexity=10 --statistics *.py
      - run:
          name: "Simple posting test"
          command: |
            python sloshy.py test-pushed.yaml "Github Actions Push test"
      - run:
          name: "Generate config for posting test"
          command: |
            python make-test-yaml.py
      - run:
          name: "Test room availability"
          command: |
            python sloshy.py room-test.yaml --test-rooms
      - run:
          name: "Announce presence in any new room"
          command: |
            python sloshy.py room-test.yaml \
               --announce "Sloshy is here! (See profile for details)"
      - run:
          name: "Clean up config file after tests"
          command: |
            rm room-test.yaml
